# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cpm < Formula
  desc "Claude Profile Manager — manage multiple Claude Code accounts"
  homepage "https://github.com/silicondawn/cpm"
  version "0.4.2"
  license "MIT"

  on_macos do
    url "https://github.com/silicondawn/cpm/releases/download/v0.4.2/cpm_darwin_amd64.tar.gz"
    sha256 "1a404948217951eaec3e8f28a2362482ffbbb088de4b442de236423f9a6ff855"

    define_method(:install) do
      bin.install "cpm"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Cpm
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/silicondawn/cpm/releases/download/v0.4.2/cpm_linux_amd64.tar.gz"
      sha256 "d06b87994508a0885da88233e0e82c9eb98fd642f9b062e2e3c8cec887129d40"
      define_method(:install) do
        bin.install "cpm"
      end
    end
  end

  test do
    system "#{bin}/cpm", "version"
  end
end
