# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cpm < Formula
  desc "Claude Profile Manager — manage multiple Claude Code accounts"
  homepage "https://github.com/silicondawn/cpm"
  version "0.5.1"
  license "MIT"

  on_macos do
    url "https://github.com/silicondawn/cpm/releases/download/v0.5.1/cpm_darwin_amd64.tar.gz"
    sha256 "77efff8ff3870340879a6227a54d2938136c6f460e1a93bb9b851e496787054e"

    define_method(:install) do
      bin.install "cpm"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Cpm
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/silicondawn/cpm/releases/download/v0.5.1/cpm_linux_amd64.tar.gz"
      sha256 "d39dc3b1f3f8ee0af046c42a88fd9cef2ea6080212a0a8e33a345709a43371b6"
      define_method(:install) do
        bin.install "cpm"
      end
    end
  end

  test do
    system "#{bin}/cpm", "version"
  end
end
