# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cpm < Formula
  desc "Claude Profile Manager — manage multiple Claude Code accounts"
  homepage "https://github.com/silicondawn/cpm"
  version "0.5.0"
  license "MIT"

  on_macos do
    url "https://github.com/silicondawn/cpm/releases/download/v0.5.0/cpm_darwin_amd64.tar.gz"
    sha256 "606252b75dcf5eaeded59ce7befd2fe2586552b0e3c0617ddce56de244f2b81c"

    define_method(:install) do
      bin.install "cpm"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Cpm
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/silicondawn/cpm/releases/download/v0.5.0/cpm_linux_amd64.tar.gz"
      sha256 "08c3234be791846977a6e6397e338339b526f8290cd982b64cac0615e0f9bf2c"
      define_method(:install) do
        bin.install "cpm"
      end
    end
  end

  test do
    system "#{bin}/cpm", "version"
  end
end
